                                                                   
////////////////////////////////////////////////////////////////////////////////// ACTOR FILMS REQUESTS



//GET FILMS OF A SPECIFIC ACTOR USING ACTOR'S ID
POST http://localhost:8080/libraryWS/getFilmsOfAnActor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:getFilmsOfAnActor>
            <actorId>1</actorId>
        </library:getFilmsOfAnActor>
    </soap:Body>
</soap:Envelope>

###


//GET FILMS OF ALL ACTORS
POST http://localhost:8080/libraryWS/getFilmsOfAllActors HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:getFilmsOfAllActors/>
    </soap:Body>
</soap:Envelope>



###

//ADD AN EXISTING FILM TO AN ACTOR USING FILM'S ID AND ACTOR'S ID
POST http://localhost:8080/libraryWS/addExistingFilmToAnExistingActor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:addExistingFilmToAnExistingActor>
            <actorId>202</actorId>
            <filmId>1</filmId>
        </library:addExistingFilmToAnExistingActor>
    </soap:Body>
</soap:Envelope>


###



//REMOVE FILM OF AN ACTOR
POST http://localhost:8080/libraryWS/removeFilmOfAnActor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:removeFilmOfAnActor>
            <actorId>1</actorId>
            <filmId>2</filmId>
        </library:removeFilmOfAnActor>
    </soap:Body>
</soap:Envelope>


###

# POST http://localhost:8080/libraryWS/removeAllFilmsActors HTTP/1.1
# Content-Type: text/xml

# <soap:Envelope
#     xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
#    xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
#     <soap:Body>
#         <library:removeAllFilmsActors/>
#     </soap:Body>
# </soap:Envelope>

###



/////////////////////////////////////////////////////////////////////////////// CUSTOMER REQUESTS


//FILTER CUSTOMER USING NAME AND/OR COUNTRY AND/OR CITY AND/OR PHONE
POST http://localhost:8080/libraryWS/filterCustomers HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:filterCustomers>
            <country>Algeria</country>
        </library:filterCustomers>
    </soap:Body>
</soap:Envelope>

###

//GET ALL CUSTOMERS
POST  http://localhost:8080/libraryWS/getAllCustomers HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:getAllCustomers/>
    </soap:Body>
</soap:Envelope>

###

//ADD CUSTOMER
POST http://localhost:8080/libraryWS/addCustomer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:addCustomer>
            <customerData>
                <firstName>hhhh</firstName>
                <lastName>ahhhli</lastName>
                <email>ahmed@yahoo</email>
                <address>
                    <address>address</address>
                    <city>cito</city>
                    <country>1</country>
                    <postalCode>000000</postalCode>
                    <district>aaaa</district>
                    <phone>01272934956</phone>
                </address>
                <active>true</active>
                <storeId>1</storeId>
            </customerData>
        </library:addCustomer>
    </soap:Body>
</soap:Envelope>

###

//REMOVE CUSTOMER
POST http://localhost:8080/libraryWS/removeCustomer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:removeCustomer>
            <id>639</id>
        </library:removeCustomer>
    </soap:Body>
</soap:Envelope>


###

//UPDATE CUSTOMER
POST http://localhost:8080/libraryWS/updateCustomer HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:updateCustomer>
            <customerData>
                <id>639</id>
                <firstName>ashraf</firstName>
                <lastName>mohsen</lastName>
                <email>ashraf@yahoo</email>
                <address>
                    <addressId>668</addressId>
                    <address>yarb</address>
                    <city>trial</city>
                    <country>1</country>
                    <postalCode>000000</postalCode>
                    <district>isa</district>
                    <phone>01273315525</phone>
                </address>
                <active>true</active>
                <storeId>1</storeId>
            </customerData>
        </library:updateCustomer>
    </soap:Body>
</soap:Envelope>

###



/////////////////////////////////////////////////////////////////////////////// FILM REQUESTS

//GET ALL FILMS
POST http://localhost:8080/libraryWS/getAllFilms HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:getAllFilms/>
    </soap:Body>
</soap:Envelope>

###







///////////////////////////////////////////ADDRESS REQUESTS
POST http://localhost:8080/libraryWS/getAllAddresses HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:getAllAddresses/>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8080/libraryWS/addAddress HTTP/1.1
Content-Type: text/xml

<soap:Envelope
xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
<soap:Body>
    <library:addAddress>
        <addressData>
            <address>hamada</address>
            <city>hamada</city>
            <country>5</country>
            <phone>01hamada</phone>
            <postalCode>020202</postalCode>
            <district>dishamada</district>
        </addressData>
    </library:addAddress>
</soap:Body>
</soap:Envelope>

###



POST http://localhost:8080/libraryWS/updateAddress HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:updateAddress>
            <addressData>
                <addressId>669</addressId>
                <address>nono</address>
                <city>ya 3adra</city>
                <country>10</country>
                <phone>01222</phone>
                <postalCode>5151</postalCode>
                <district>popo</district>
            </addressData>
        </library:updateAddress>
    </soap:Body>
</soap:Envelope>

###


///////////////////////////////////////////INVENTORY REQUESTS

POST http://localhost:8080/libraryWS/getAllInventories HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:getAllInventories/>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8080/libraryWS/addInventory HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:addInventory>
            <inventoryData>
                <filmId>5</filmId>
               <storeId>2</storeId>
            </inventoryData>
        </library:addInventory>
    </soap:Body>
</soap:Envelope>

###



POST http://localhost:8080/libraryWS/updateInventory HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:updateInventory>
            <inventoryData>
                <inventoryId>4638</inventoryId>
                <filmId>10</filmId>
                <storeId>1</storeId>
            </inventoryData>
        </library:updateInventory>
    </soap:Body>
</soap:Envelope>

###


POST http://localhost:8080/libraryWS/removeInventory HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:removeInventory>
            <inventoryId>4638</inventoryId>
        </library:removeInventory>
    </soap:Body>
</soap:Envelope>


###

///////////////////////////////////STORE REQUESTS


POST http://localhost:8080/libraryWS/getAllStores HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:getAllStores/>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8080/libraryWS/addStore HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:addStore>
            <storeData>
                <managerId>5</managerId>
                <address>
                    <address>kqkqkq</address>
                    <city>klkp</city>
                    <country>1</country>
                    <postalCode>000000</postalCode>
                    <district>alala</district>
                    <phone>0101273315525</phone>
                </address>
            </storeData>
        </library:addStore>
    </soap:Body>
</soap:Envelope>

###



POST http://localhost:8080/libraryWS/updateStore HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:updateStore>
            <storeData>
                <storeId>4</storeId>
                <managerId>3</managerId>
                <address>
                    <addressId>671</addressId>
                    <address>store address2</address>
                    <city>aaa</city>
                    <country>6</country>
                    <postalCode>000000</postalCode>
                    <district>aaaa</district>
                    <phone>01273315525</phone>
                </address>
            </storeData>
        </library:updateStore>
    </soap:Body>
</soap:Envelope>

###





///////////////////////////////////ACTOR REQUESTS


POST http://localhost:8080/libraryWS/getAllActors HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:getAllActors/>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8080/libraryWS/addActor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:addActor>
            <actorData>
                <firstName>hassan</firstName>
                <lastName>hossny</lastName>
            </actorData>
        </library:addActor>
    </soap:Body>
</soap:Envelope>

###



POST http://localhost:8080/libraryWS/updateActor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:updateActor>
            <actorData>
                <id>202</id>
                <firstName>tamer</firstName>
                <lastName>hossny</lastName>
            </actorData>
        </library:updateActor>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8080/libraryWS/removeActor HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:removeActor>
                <id>202</id>
        </library:removeActor>
    </soap:Body>
</soap:Envelope>
###

/////////////////////////////////CITY REQUESTS

POST http://localhost:8080/libraryWS/getAllCities HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:getAllCities/>
    </soap:Body>
</soap:Envelope>

###

POST http://localhost:8080/libraryWS/addCity HTTP/1.1
Content-Type: text/xml

<soap:Envelope
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:library="http://services.jaxws.filmslibrary.jets.iti.gov/">
    <soap:Body>
        <library:addCity>
            <cityData>
                <city>new city</city>
                <countryId>3</countryId>
            </cityData>
        </library:addCity>
    </soap:Body>
</soap:Envelope>